### ISSUE TITLE
Use an internal slot rather than a symbol

### ISSUE THREAD

**Issue by littledan** [mikesamuel/evalable#2]
I don't think adding additional well-known symbols is a good extension point here, because:
- The property access is observable
- There is significant implementation burden to implement without performance overhead

Neither of these are 100% fatal on their own, but we have alternatives here which wouldn't face these issues.

In particular, I'd suggest an internal slot, `[[Evalable]]`, which is present on objects which should return true for IsCodeLike. Trusted types would say that the trusted eval strings it creates have this internal slot.

(If we want to go crazy, you can also make a class, `Evalable` which returns an object which has this internal slot, and can be subclassed to let custom objects be eval-able, but I'm not sure if we need to extend this beyond trusted types.)

**Comment by mikesamuel** [comment]
> The property access is observable

Good point.

> In particular, I'd suggest an internal slot, [[Evalable]], which is present on objects which should return true for IsCodeLike. Trusted types would say that the trusted eval strings it creates have this internal slot.

I'm fine with that.
I'll draft that as well and use the stage 1 preso to mention that we have options.
If people for some reason ask for a symbol, I'll have spec text with a symbol.
My argument for stage 2 will be that we have spec texts and which variant needs to be solved for 3.

Any preference for [[Evalable]] over [[CodeLike]] which IsCodeLike evokes more?

Any preference for testing *has* slot vs testing for truthiness of the slot's value?


> There is significant implementation burden to implement without performance overhead

I don't quite understand the performance angle but think your point about property access is sufficient.

Since "If Type(*x*) is String" is on the fast path through IsCodeLike, none of this should affect the performance of `eval` as applied to strings.

It could affect the performance of `eval` applied to non-string but I suspect that rarely happens so I'm unconvinced there'd be a performance issue in practice.


> (If we want to go crazy, you can also make a class, Evalable which returns an object which has this internal slot, and can be subclassed to let custom objects be eval-able, but I'm not sure if we need to extend this beyond trusted types.)

+1 TT doesn't need it but it's nice to know that anyone who needs to would find a path half laid.

**Comment by littledan** [comment]
Thanks for being so receptive to the suggestion. About the bikeshedding questions, I would suggest \[\[CodeLike]] and testing for presence, to start, but I don't have a strong opinion.
